/*
	LotJ Chargen Custom JS
	for use with LotJ Chargen
	by @Xerakon
	http://xerakon.com/lotj
	chargen.js
	Version 1.0
*/

const headingList = [
  "I'm going to be a",
  "How about a",
  "My new character is a",
];

const adjectiveList = [
  "absent minded",
  "adventurous",
  "agreeable",
  "ambitious",
  "amicable",
  "anxious",
  "apathetic",
  "argumentative",
  "assertive",
  "attentive",
  "bigoted",
  "bitchy",
  "blunt",
  "boisterous",
  "bossy",
  "brave",
  "broad-minded",
  "callous",
  "cautious",
  "charming",
  "cheerful",
  "chipper",
  "churlish",
  "cold",
  "compassionate",
  "composed",
  "conceited",
  "condescending",
  "confident",
  "conscientious",
  "considerate",
  "cool-headed",
  "courageous",
  "crabby",
  "crass",
  "critical",
  "cruel",
  "cunning",
  "curious",
  "cynical",
  "decisive",
  "delightful",
  "demure",
  "dependable",
  "depressed",
  "determined",
  "diligent",
  "diplomatic",
  "discerning",
  "disruptive",
  "dramatic",
  "driven",
  "dutiful",
  "eager",
  "easy-going",
  "egotistical",
  "emotional",
  "enterprising",
  "enthusiastic",
  "excitable",
  "faithful",
  "fearless",
  "flamboyant",
  "flirtatious",
  "frank",
  "friendly",
  "funny",
  "fussy",
  "generous",
  "gentle",
  "gloomy",
  "grave",
  "grouchy",
  "gruff",
  "guarded",
  "hard-working",
  "hateful",
  "headstrong",
  "helpful",
  "hot-headed",
  "hot-headed",
  "hypercritical",
  "impatient",
  "impetuous",
  "impulsive",
  "inconsiderate",
  "insensitive",
  "intolerant",
  "inventive",
  "irritable",
  "lazy",
  "level-headed",
  "loud",
  "Machiavellian",
  "mean",
  "melodramatic",
  "methodical",
  "meticulous",
  "miserable",
  "modest",
  "moody",
  "morose",
  "motivated",
  "naive",
  "nosy",
  "obnoxious",
  "old-fashioned",
  "outgoing",
  "outspoken",
  "overemotional",
  "paranoid",
  "passive-aggressive",
  "peaceful",
  "pensive",
  "philosophical",
  "plain-speaking",
  "playful",
  "plucky",
  "pompous",
  "positive",
  "prejudiced",
  "pretty chill",
  "proud",
  "quick-tempered",
  "reliable",
  "reluctant",
  "resentful",
  "resourceful",
  "respectful",
  "restless",
  "romantic",
  "sassy",
  "selfish",
  "sensitive",
  "sentimental",
  "short-tempered",
  "snobby",
  "sombre",
  "sophisticated",
  "soulless",
  "spiteful",
  "stern",
  "stoic",
  "surly",
  "suspicious",
  "sweet",
  "tactless",
  "talented",
  "thoughtful",
  "unbalanced",
  "unpredictable",
  "unstable",
  "warm-hearted",
  "wary",
  "wary",
  "well-intentioned",  
];

const raceList = [
  "Abednedo",
  "Abyssin",
  "Alderaanian",
  "Aqualish",
  "Ardennian",
  "Arkanian",
  "Astromech",
  "Balosar",
  "Barabel",
  "Baragwin",
  "Besalisk",
  "Bith",
  "Bothan",
  "Cathar",
  "Cerean",
  "Chagrian",
  "Chiss",
  "Corellian",
  "Dashade",
  "Defel",
  "Devaronian",
  "Draethos",
  "Dug",
  "Duros",
  "Echani",
  "Falleen",
  "Feeorin",
  "Firrerreo",
  "Gamorrean",
  "Gand",
  "Geonosian",
  "Givin",
  "Gotal",
  "Gran",
  "Gungan",
  "Human",
  "Hutt",
  "Iakaru",
  "Iktotchi",
  "Ithorian",
  "Jawa",
  "Kaleesh",
  "Kaminoan",
  "Kel_dor",
  "Khommite",
  "Kiffar",
  "Kubaz",
  "Lannik",
  "Lasat",
  "Lorrdian",
  "Mandalorian",
  "Miraluka",
  "Mirialan",
  "Mon_calamari",
  "Muun",
  "Naboo",
  "Nautolan",
  "Neimoidian",
  "Nikto",
  "Noghri",
  "Omwati",
  "Pau'an",
  "Protocol_droid",
  "Quarren",
  "Quermian",
  "Rodian",
  "Ryn",
  "Sith",
  "Sluissi",
  "Sullustan",
  "Talz",
  "Togruta",
  "Toong",
  "Toydarian",
  "Trandoshan",
  "T'Surr",
  "Twi'lek",
  "Ubese",
  "Ugnaught",
  "Umbaran",
  "Utai",
  "Verpine",
  "Vurk",
  "Weequay",
  "Whiphid",
  "Wookiee",
  "Wroonian",
  "Zabrak",
  "Zeltron",  
];

const jobList = [
  "arms dealer",
  "assassin",
  "barkeep",
  "big game hunter",
  "bio science engineer",
  "bodyguard",
  "bodyguard",
  "bounty hunter",
  "brawler",
  "caterer",
  "combat medic",
  "commando",
  "con artist",
  "contraband dealer",
  "coordinator",
  "courier",
  "courtier",
  "cryptographer",
  "cybernetic artist",
  "datachip manufacturer",
  "deep space explorer",
  "developer",
  "diplomat",
  "diplomatic aide",
  "doctor",
  "double agent",
  "drug dealer",
  "electronic warfare specialist",
  "energy weapons technicians",
  "engineer",
  "espionist",
  "extraction specialist",
  "fence",
  "fighter",
  "fleet commander",
  "fleet officer",
  "forger",
  "freelance information broker",
  "fugitive recovery technicians",
  "grenadier",
  "grifter",
  "gunship captain",
  "hacker",
  "hired gun",
  "hitman",
  "holonet influencer",
  "holonet tracer",
  "informant",
  "inventor",
  "journalist",
  "leader",
  "logistics coordinator",
  "medical supply specialist",
  "mercenary",
  "mobile triage physician",
  "naval tactician",
  "network specialist",
  "news anchor",
  "nurse",
  "on-scene reporter",
  "operative",
  "operative",
  "physicist",
  "pirate",
  "pirate holonet show host",
  "pirate hunter",
  "police officer",
  "professor",
  "propagandist",
  "researcher",
  "restaurateur",
  "robotics engineer",
  "saboteur",
  "safe house operator",
  "sapper",
  "scientist",
  "scout",
  "scout-sniper",
  "security analyst",
  "security guard",
  "security specialist",
  "serial killer",
  "shield generator specialist",
  "ship mechanic",
  "ship systems technician",
  "sketchy 'ripper doc' cybernetic implanter",
  "slicer",
  "smuggler",
  "snubfighter ace",
  "snubfighter pilot",
  "spy",
  "spy equipment shopkeep",
  "strategist",
  "structural engineer",
  "surgeon",
  "surveillance specialist",
  "theoretical scientist",
  "tracker",
  "tramp freighter hauler",
  "turret gunnery specialist",
  "undercover agent",
  "veteran",  
];

const locationList = [
  "a backwater village",
  "a boarding school for the children of middle-class bureaucrats",
  "a boarding school",
  "a broken home",
  "a bustling city market",
  "a bustling city",
  "a bustling underground colony",
  "a Calamari floating city",
  "a camp of frontier planet colonists",
  "a carnival freak show",
  "a children's workhouse",
  "a city in the shifting sands of Tatooine",
  "a city no one else has ever heard of",
  "a city that never slept on Nar Shaddaa",
  "a city that was thoroughly-bombarded in the last galactic war",
  "a city with towers that rival the clouds",
  "a cliff-side village",
  "a complex bureaucratic society",
  "a conquered city",
  "a contraband spice freighter",
  "a Corellian brewery",
  "a cultist colony in a cavern without echoes",
  "a cursed village",
  "a desert town hidden within the Dune Sea",
  "a deserted island",
  "a destitute tuber plantation",
  "a destroyed city",
  "a dilapidated mansion",
  "a dingy town on the nocturnal side of Ryloth",
  "a disgraced Jawa clan",
  "a drought-stricken farm",
  "a dysfunctional marriage",
  "a fallen backwater kingdom",
  "a filthy den full of spice addicts",
  "a fishing village on Wroona",
  "a floating shanty town",
  "a foggy peninsula on Alderaan",
  "a forgotten Jedi monastery",
  "a free thinkers commune",
  "a frozen jungle",
  "a frozen wasteland",
  "a gangster-run orphanage",
  "a haberdashery",
  "a halfway house",
  "a hastily erected tent city on Nal Hutta",
  "a hidden grotto on Mon Cala",
  "a high end gambling house on Nar Shaddaa",
  "a laid back beach town",
  "a large and prosperous Alderaanian nerf farm",
  "a large desert metropolis",
  "a large family",
  "a line of fallen royalty",
  "a low ceilinged manor",
  "a man made desert",
  "a maximum security prison on Kessel",
  "a mercenary outfit",
  "a mining town",
  "a moving island",
  "a nomad circus",
  "a notorious gangster's harem",
  "a now impoverished noble family",
  "a orphanage workhouse",
  "a peaceful coastal town ",
  "a pirate nest",
  "a pirate-controlled town",
  "a place only they can pronounce",
  "a plague ridden city",
  "a poor Nabooian dairy farm",
  "a poorly run orphanage",
  "a potentially haunted forest",
  "a powerful trading town",
  "a quaint little village on a hill",
  "a quiet woodland hut",
  "a recently erupted volcano village",
  "a refugee camp for war orphans",
  "a religious extremist temple",
  "a royal lineage",
  "a ruined city",
  "a run-down tavern",
  "a Rylothian high-class brothel",
  "a secluded forest village",
  "a secret brawler's guild in the Coruscanti underground",
  "a secret order of B'omarr monks",
  "a sheltered upbringing",
  "a sleepy harbour town",
  "a small family bakery",
  "a small family farm",
  "a small farm in the grasslands",
  "a small remote village",
  "a small town on a Mid Rim planet",
  "a small town tavern",
  "a small town where nothing ever happened",
  "a strict monastery",
  "a string of terrible places to live",
  "a sunken city",
  "a super religious upbringing",
  "a Tatooine swoop gang",
  "a theatre company",
  "a thriving seaport town on Wroona",
  "a tiny homestead on Dantooine",
  "a tiny loft above a storefront in Adascopolis, Arkania",
  "a tiny village on Ord Mantell",
  "a tourist town in the mountains of Lorrd",
  "a trading tramp freighter",
  "a tramp freighter",
  "a tropical paradise",
  "a very tiny province",
  "a war-torn city",
  "a wealthy vineyard",
  "a young offenders institute",
  "an adoptive Mandalorian warrior clan camp",
  "an affluent upbringing",
  "an ancient monastery",
  "an aristocratic family",
  "an asylum",
  "an impure bloodline",
  "an internment camp",
  "an island long thought to be uninhabited",
  "an isolated Kashyyykian tree village",
  "an isolated monastery ",
  "an Ithorian herdship",
  "an oasis village",
  "an outlaw town controlled by smugglers",
  "an spacer engineer's guild",
  "an unchartable planet in Wild Space",
  "an underground bunker of a doomed cult",
  "an underground city",
  "an underground military stronghold",
  "an underwater monastery",
  "from a city deep under the mountains",
  "the badlands of Ryloth",
  "the base of a volcano on Mustafar",
  "the Desolation Alley prison colony",
  "the library-planet of Obroa-skai",
  "the pilot's guild",
  "the planet-city of Coruscant",
  "the wealthy play-planet of Canto Bite",
  "Wroona's Black Rock Cove",
];

const backstoryList = [
  "acts shallow but only to hide their insecurities",
  "adds a notch to their weapon every night",
  "aims to learn every language in the galaxy, but is terrible with linguistics",
  "already made and lost a fortune",
  "always alliterates their anecdotes",
  "always cuts to the chase",
  "always gives the bad news first",
  "always gives the good news first",
  "always keeps their promises",
  "always looks their best",
  "always needs to be the center of attention",
  "always refers to inanimate objects as 'she'",
  "always romanticised adventure",
  "always speaks in the third person",
  "always thinks outside the box",
  "always wakes up on the right side of the bed",
  "always wanted to be an artist",
  "bangs on about their genealogy to everyone",
  "believes class III armor is just a sign of being posh and over-privileged",
  "believes in an eye for an eye",
  "believes that if they try hard enough, they can access the Force",
  "believes they have a claim to the throne",
  "believes they were born in a different body",
  "believes they're a demi god, but hasn't figured out who their father is yet",
  "believes trees can speak to them and them alone",
  "can't read",
  "can't seem to hold their liquor",
  "can't silence the voices",
  "can't sleep indoors",
  "can't stand children",
  "can't stand silence",
  "can't stand the sight of blood",
  "can't stand to wear armor",
  "can't swim",
  "carries a charmed locket that they can't open",
  "carries a cryptic treasure map they won in a tavern bet",
  "carries the skull of their best friend",
  "constantly places themselves in danger, just to prove a point",
  "constantly watches their back",
  "deserted an army",
  "distrusts all authority",
  "doesn't believe in hygiene",
  "doesn't believe in the Force, ever",
  "doesn't know their own strength",
  "doesn't perceive gender",
  "doesn't speak a word of basic",
  "doesn't understand sarcasm",
  "doesn't understand the concept of politeness",
  "drunkenly swore a blood oath and forgot what for",
  "exaggerates everything they talk about",
  "failed out of 3 other class academies before settling on their main",
  "fights for Jawa rights",
  "fights for species equality",
  "finds armor too restricting",
  "finds it impossible to speak to girls",
  "forever picking fights to 'win back honour'",
  "gets easily attached to people",
  "gets nervous speaking in front of crowds",
  "grew up fat",
  "grew up in a graveyard",
  "had their lost legs replaced with droid treads",
  "had their nose cut off in a duel",
  "has a bad gambling problem",
  "has a bad habit of making 'funny' quips after every kill",
  "has a burning hatred for pirates",
  "has a childhood dream to become a juggler",
  "has a debilitating fear of wide open spaces",
  "has a drinking problem",
  "has a huge debt to pay back",
  "has a poem for all occasions",
  "has a pretty selective memory",
  "has a regular sleepwalking issue",
  "has a serious weapons fetish",
  "has a twin that constantly impersonates them",
  "has accepted death as an inevitability",
  "has always wanted to open their own tavern",
  "has an outstanding warrant for their arrest on their homeworld",
  "has anger problems",
  "has been exiled from their homeworld twice under different names",
  "has been on the run for over three years",
  "has cheated death more times than they deserved",
  "has delusions of grandeur",
  "has durasteel teeth after the incident with the forcepike",
  "has gotten away with murder",
  "has had it up to here with everyone's crap",
  "has never been kissed",
  "has never had their hair cut",
  "has no concept of personal space",
  "has no sense of smell",
  "has nothing left to lose",
  "has really bad allergies on every other planet",
  "has serious body image problems",
  "has serious daddy issues",
  "has some pretty shady connections",
  "has taken a vow of silence",
  "has twenty-seven siblings to provide for",
  "hasn't accomplished anything in their short life yet",
  "hasn't been quite right since the accident",
  "hates being made to wait",
  "hates flying aboard spaceships",
  "hates music",
  "hates the idea of monarchies",
  "hates the written word",
  "hates to be clean",
  "hates to be touched",
  "hates wearing their glasses",
  "in hindsight shouldn't have had their ship hatch code tattooed on themselves",
  "insists they are the reincarnation of a legendary warrior",
  "is a compulsive liar",
  "is a former bare knuckle boxer",
  "is a recovering cannibal",
  "is a recovering gambling addict",
  "is afraid of fire",
  "is afraid of heights",
  "is afraid of pets",
  "is afraid of sharp edges",
  "is being hunted by a notorious bounty hunter",
  "is certain their days are numbered",
  "is completely and utterly tone-deaf",
  "is completely color blind",
  "is convinced they're always being left out",
  "is currently on probation for drunk and disorderly behaviour",
  "is cursed to speak in sentences of exactly ten words",
  "is dealing with a midlife crisis",
  "is deathly afraid of space flight",
  "is downright racist towards every other race",
  "is dying of a plague and searching for a cure",
  "is getting too old for all this",
  "is haunted by the ghost of their father",
  "is haunted by the ghosts of their forefathers",
  "is haunted by the ghosts of those they kill",
  "is in so far over their head that they can't help but laugh",
  "is in way too deep with the wrong sort of people",
  "is just trying to get by",
  "is lactose intolerant",
  "is manically obsessed with etiquette",
  "is on the run after having an affair with a noble's daughter",
  "is planning to retire next year",
  "is posing as someone else",
  "is pretty tight fisted with their gold",
  "is quick to take credit and assign blame",
  "is really (I MEAN REALLY) afraid of the dark",
  "is really good at bribing officials",
  "is red-green colorblind",
  "is responsible for their sister's death",
  "is running from a marriage arranged by their parents",
  "is searching for a rare fertility herb",
  "is searching for the knowledge of true immortality",
  "is searching for the perfect culinary dish",
  "is secretly fond of embroidery",
  "is terrified of slimy or tiny creatures",
  "is the last of a king's bastard children",
  "is the last of an ancient bloodline",
  "is the twin of a backwater planet's reigning monarch",
  "is tracking down the treasure their father died trying to find",
  "is trapped in a Faustian bargain",
  "is trying to avoid a prophecy",
  "is trying to dodge the draft on their homeworld",
  "is trying to get out of their current business to settle down",
  "is uncomfortable around old people (they smell like death)",
  "is wanted for a reward",
  "is writing an autobiography",
  "is writing an epic poem about their galactic adventure",
  "keeps a blacklist",
  "keeps getting mistaken for a famous bounty hunter - and encourages this resemblance",
  "killed their brother in a duel over their inheritance",
  "knows seven dangerous secrets",
  "left their home in disgrace",
  "likes to settle arguments with an arm wrestle",
  "likes to settle arguments with headbutting contests",
  "likes to speak in rhyme",
  "loots every kill but leaves enough to pay for their burial",
  "lost minor appendages due to their gambling addiction",
  "lost their best friend in an ambush",
  "lost their family in a mynock attack ",
  "lost their marbles a long time ago",
  "lost their sense of smell in a bar fight",
  "lost two fingers in a training accident",
  "loved, lost and never loved again",
  "loves to haggle",
  "makes all minor decisions by flipping a coin",
  "makes inappropriate jokes at the worst times",
  "meditates before dawn",
  "mistrusts anyone smaller than them",
  "mistrusts anyone taller than them",
  "moonlights as a private investigator",
  "names every piece of their gear",
  "never got the proper training",
  "never passes up a chance to say, 'I told you so.'",
  "never returned anything they borrowed",
  "never takes their armor off, just in case",
  "never turns the other cheek",
  "no longer dreams",
  "once survived a boiling cauldron surrounded by cannibals",
  "only sleeps with the lights on",
  "owes money to the wrong people",
  "parties hard, way too hard.",
  "prefers to fight drunk",
  "ran afoul of a swoop gang as a child",
  "ran away at the age of eleven",
  "realised the importance of literacy far too late in life",
  "really knows how to party",
  "refuses to admit they're past their prime",
  "refuses to bathe",
  "rejected a Senator's marriage proposal",
  "saw their whole family consumed by an alien resembling a gelatinous cube",
  "searches endlessly for their kidnapped child",
  "secretly became an datapad collector to impress a love interest",
  "seeks to end a family feud",
  "seems to know everyone",
  "started a rebellion in their last place of employment",
  "suffers from a recurring nightmare",
  "suffers from claustrophobia",
  "suffers from crippling stage-fright",
  "suffers from night terrors",
  "suffers from nosebleeds",
  "takes great delight in identifying new beetle species",
  "thinks they can read the future, but consistently gets it wrong",
  "tries to be a friend to everyone",
  "unwittingly misuses words all the bloody time",
  "used to work as a tavern bouncer",
  "wants everyone to like them",
  "wants to be famous, no matter what",
  "wants to become a famous singer",
  "wants to clear their name",
  "wants to prove they're no longer that goofy kid",
  "wants to smash the capitalist system",
  "was a turret gunner on a famous warship that finally ran into an asteroid - and won't shut up about it",
  "was apprenticed to a failed engineer",
  "was badly bitten by a mynock",
  "was beaten and imprisoned for their religious beliefs",
  "was brought up to be a librarian",
  "was cut from their dead mother's womb",
  "was disowned by their family",
  "was drafted into the army at fourteen",
  "was exiled by their brother, the king of their homeworld",
  "was expelled from a contingent of royal guards",
  "was forced to watch their families execution",
  "was framed for the murder of a famous and well-loved innkeeper",
  "was jailed for a crime they didn't commit",
  "was kidnapped by cultists",
  "was left out of their father's will",
  "was petrified for over two hundred years",
  "was raised as a hostage by their father's enemies",
  "was raised by ghosts",
  "was told they'll never be good enough",
  "was written out of their family will",
  "was, until recently, employed to run a brothel",
  "woke up in a bar with no memory and a sealed letter",
  "won a duel they were supposed to lose out of sheer luck",
  "worries some of their memories have been tampered with",
  "would rather kill you than make eye contact",
];

const responseList = [
  "Eh... Give me another one",
  "I don't really care about that guy",
  "I've already roleplayed that one",
  "That doesn't make any sense",
  "That sounds terrible",  
];

function generateIdea() {
  const heading = headingList[Math.floor(Math.random() * headingList.length)];
  const adjective = adjectiveList[Math.floor(Math.random() * adjectiveList.length)];
  const race = raceList[Math.floor(Math.random() * raceList.length)];
  const job = jobList[Math.floor(Math.random() * jobList.length)];
  const location = locationList[Math.floor(Math.random() * locationList.length)];
  const backstory = backstoryList[Math.floor(Math.random() * backstoryList.length)];
  const response = responseList[Math.floor(Math.random() * responseList.length)];
  const chargenString = adjective + " " + race + " " + job + " from " + location + " who " + backstory;

  $("#headingDisplay").html(heading);
  $("#chargenDisplay").html(chargenString);
  $("#responseDisplay").html(response);
}

//const showraceJson = require("./lotj/js/showrace.json")

let races = []

async function getRaces() {
  const response = await fetch('./js/showrace.json');
  races = await response.json();

  //console.log(races);
}

jQuery(document).ready(function($){
  /*
  let showraceJson = fetch('./js/showrace.json')
    .then((response) => response.json())
    .then((json) => console.log(json));
    */
  //const obj = JSON.parse(showraceJson);
  //$("#testArea").html(obj.name);

  
  $("#responseDisplay").on("click", function() {
    generateIdea();
  });
  generateIdea();
  getRaces();
  console.log(races);
});	//jquery ready